[package]
name = "one-brc-rust"
version = "0.1.0"
edition = "2024"

[profile.profiling]
inherits = "release"
debug = true

[dependencies]
memchr = "2.7.5"
memmap2 = "0.9.7"
rustc-hash = "2.1.1"

[dev-dependencies]
